name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=calculator --cov-report=xml:coverage.xml --junitxml=test-results.xml
        
    - name: Move artifacts to docs folder
      run: |
        mkdir -p docs
        mv test-results.xml coverage.xml docs/
        

    - name: Commit artifacts to docs branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action agent docs"
        git checkout -B docs
        git add docs/test-results.xml docs/coverage.xml
        git commit -m "Update test artifacts in docs folder" || echo "No changes to commit"
        git push origin docs --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
