name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      continue-on-error: true
      run: |
        pytest tests/ --cov=calculator --cov-report=xml:coverage.xml --junitxml=test-results.xml
    
    - name: Set up Git for pushing reports
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
    
    - name: Checkout docs branch
      uses: actions/checkout@v4
      with:
        ref: docs
        path: docs-branch
    
    - name: Copy test reports to docs directory
      run: |
        mkdir -p docs-branch/docs
        cp coverage.xml test-results.xml docs-branch/docs/
    
    - name: Commit and push test reports to docs branch
      run: |
        cd docs-branch
        git add docs/coverage.xml docs/test-results.xml
        git commit -m "Update test reports from CI run"
        git push origin docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
